name: popgenomics
channels:
  - jluquette
  - bioconda
  - R
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.0
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - amply=0.1.4
  - appdirs=1.4.4
  - async-timeout=4.0.2
  - atk-1.0=2.36.0
  - attmap=0.13.2
  - attrs=21.4.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcftools=1.14
  - bcrypt=3.2.0
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - boto3=1.20.35
  - botocore=1.23.35
  - bowtie2=2.4.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.10
  - click=8.0.3
  - coincbc=2.10.5
  - colorama=0.4.4
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - commonmark=0.9.1
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - cryptography=36.0.1
  - curl=7.81.0
  - cycler=0.11.0
  - dataclasses=0.8
  - datrie=0.8.2
  - docutils=0.18.1
  - drmaa=0.7.9
  - dropbox=11.25.0
  - expat=2.4.2
  - fastqc=0.11.9
  - fftw=3.3.10
  - filechunkio=1.8
  - filelock=3.4.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.28.5
  - freetype=2.10.4
  - fribidi=1.0.10
  - frozenlist=1.2.0
  - ftputil=5.0.2
  - future=0.18.2
  - gatk=3.8
  - gatk4=4.2.4.1
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gdk-pixbuf=2.42.6
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - ghostscript=9.54.0
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.26
  - google-api-core=2.4.0
  - google-api-python-client=2.35.0
  - google-auth=2.3.3
  - google-auth-httplib2=0.1.0
  - google-cloud-core=2.2.1
  - google-cloud-storage=2.0.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.1.0
  - googleapis-common-protos=1.54.0
  - graphite2=1.3.13
  - graphviz=2.49.0
  - grpcio=1.42.0
  - gsl=2.6
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - harfbuzz=3.1.1
  - htslib=1.14
  - httplib2=0.20.2
  - humanfriendly=10.0
  - icu=68.2
  - idna=3.1
  - imagemagick=7.0.11_13
  - importlib-metadata=4.10.0
  - importlib_resources=5.4.0
  - iniconfig=1.1.1
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jinja2=3.0.3
  - jmespath=0.10.0
  - jpeg=9d
  - jsonschema=4.4.0
  - jupyter_core=4.9.1
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.81.0
  - libdeflate=1.9
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=11.2.0
  - libgd=2.3.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.19.3
  - librsvg=2.52.5
  - libsanitizer=9.4.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.11
  - logmuse=0.2.6
  - lz4-c=1.9.3
  - lzstring=1.0.4
  - make=4.3
  - markdown=3.3.6
  - markupsafe=2.0.1
  - matplotlib-base=3.5.1
  - multidict=5.2.0
  - multiqc=1.11
  - munkres=1.1.4
  - natefoo-slurm-drmaa=1.2.0_dev_deca826
  - nbformat=5.1.3
  - ncurses=6.2
  - networkx=2.6.3
  - numpy=1.22.0
  - oauth2client=4.1.3
  - olefile=0.46
  - openjdk=8.0.312
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.3.5
  - pango=1.48.10
  - paramiko=2.9.2
  - pcre=8.45
  - pcre2=10.36
  - peppy=0.31.2
  - perl=5.32.1
  - picard=2.26.10
  - pillow=8.2.0
  - pip=21.3.1
  - pixman=0.40.0
  - pkg-config=0.29.2
  - pluggy=1.0.0
  - ply=3.11
  - prettytable=3.0.0
  - protobuf=3.19.3
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pulp=2.6.0
  - py=1.11.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.11.2
  - pygraphviz=1.7
  - pynacl=1.5.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyrsistent=0.18.0
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=6.2.5
  - python=3.9.9
  - python-dateutil=2.8.2
  - python-irodsclient=1.0.0
  - python_abi=3.9
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.0.5
  - r-bitops=1.0_7
  - r-brio=1.1.3
  - r-callr=3.7.0
  - r-catools=1.18.2
  - r-cli=3.1.0
  - r-colorspace=2.0_2
  - r-crayon=1.4.2
  - r-desc=1.4.0
  - r-diffobj=0.3.5
  - r-digest=0.6.29
  - r-ellipsis=0.3.2
  - r-evaluate=0.14
  - r-fansi=1.0.2
  - r-farver=2.1.0
  - r-ggplot2=3.3.5
  - r-glue=1.6.0
  - r-gplots=3.1.1
  - r-gsalib=2.1
  - r-gtable=0.3.0
  - r-gtools=3.9.2
  - r-isoband=0.2.5
  - r-jsonlite=1.7.2
  - r-kernsmooth=2.23_20
  - r-labeling=0.4.2
  - r-lattice=0.20_45
  - r-lifecycle=1.0.1
  - r-magrittr=2.0.1
  - r-mass=7.3_55
  - r-matrix=1.4_0
  - r-mgcv=1.8_38
  - r-munsell=0.5.0
  - r-nlme=3.1_155
  - r-pillar=1.6.4
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.4
  - r-plyr=1.8.6
  - r-praise=1.0.0
  - r-processx=3.5.2
  - r-ps=1.6.0
  - r-r6=2.5.1
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.8
  - r-rematch2=2.1.2
  - r-reshape=0.8.8
  - r-rlang=0.4.12
  - r-rprojroot=2.0.2
  - r-rstudioapi=0.13
  - r-scales=1.1.1
  - r-testthat=3.1.1
  - r-tibble=3.1.6
  - r-utf8=1.2.2
  - r-vctrs=0.3.8
  - r-viridislite=0.4.0
  - r-waldo=0.3.1
  - r-withr=2.4.3
  - ratelimiter=1.2.0
  - readline=8.1
  - requests=2.27.1
  - rich=11.0.0
  - rsa=4.8
  - s3transfer=0.5.0
  - samtools=1.3.1
  - scipy=1.7.3
  - sed=4.8
  - setuptools=59.8.0
  - simplejson=3.17.6
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=5.2.1
  - smmap=3.0.5
  - snakemake=6.13.0
  - snakemake-minimal=6.13.0
  - spectra=0.0.11
  - sqlite=3.37.0
  - stone=3.2.1
  - stopit=1.1.2
  - sysroot_linux-64=2.12
  - tabulate=0.8.9
  - tbb=2020.2
  - tk=8.6.11
  - tktable=2.10
  - toml=0.10.2
  - toposort=1.7
  - traitlets=5.1.1
  - trimmomatic=0.36
  - typing-extensions=4.0.1
  - typing_extensions=4.0.1
  - tzdata=2021e
  - ubiquerg=0.6.1
  - uritemplate=4.1.1
  - urllib3=1.26.8
  - vcftools=0.1.16
  - veracitools=0.1.3
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wrapt=1.13.3
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9

