---
title: "SNP associations"
author: "Lea Stauber - Stauber et al. 2022, Mol. Ecol."
date: "1/14/2022"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!requireNamespace("renv", quietly = TRUE))
    install.packages("renv")


## to restore R environment from renv.lock file run:
# renv::restore()

library(ggplot2)
library(dplyr)

```

### Plot interval for removal of mating type associated SNPs
```{r removal MAT SNPs, message=FALSE, warning=FALSE}
tasseldfMAT <- read.table("../data/TASSEL_AssociationStudy_MAT_pvalues.txt", sep = "\t", header = T)
scaf2 <- filter(tasseldfMAT, Chr == "2" & marker_F !=Inf)

region <- filter(scaf2, Pos >= 200000 & Pos <= 1800000)

sig <- filter(region, p <= 1*10^-6)
min <- min(sig$Pos)
max <- max(sig$Pos)

ggplot(scaf2, aes(x=(Pos/1000), y=-log10(p))) + geom_point(color="darkgrey") + theme_bw() + scale_x_continuous(breaks = seq(0, 7500, 200)) +
  xlab("Scaffold 2, Position [kb]") + theme(axis.text.x=element_text(angle = 45, hjust = 1, size=7)) +
  geom_hline(yintercept=-log10(1*10^-6), color="red", size=1, linetype="dashed") + 
  geom_vline(xintercept = (min/1000), col="blue") + 
  annotate("text", x = 20, y = 75, angle = 90, label = "292'413 bp", size=4) + 
  geom_vline(xintercept = (max/1000), col="blue") +
  annotate("text", x = 2300, y = 75, angle = 90, label = "1'775'781 bp", size=4)

dir.create("plots")

ggsave("plots/SupplFig1_MAT.associations.pdf", height = 5, width = 5)
```


### Plot vic associated SNPs

```{r removal MAT SNPs, message=FALSE, warning=FALSE}
tasseldfVIC <- read.table("../data/TASSEL_AssociationStudy_vic_pvalues.txt", sep = "\t", header = T, na.strings = "NaN")

## get positions for highly associated SNPs
vic_SNPs <- tasseldfVIC %>% 
  group_by(Trait) %>% 
  summarise(associated_SNP_p = min(p, na.rm = T)) %>% 
  mutate(Chr = tasseldfVIC$Chr[match(interaction(Trait, associated_SNP_p),interaction(tasseldfVIC$Trait, tasseldfVIC$p))],
         Pos = tasseldfVIC$Pos[match(interaction(Trait, associated_SNP_p),interaction(tasseldfVIC$Trait, tasseldfVIC$p))]) %>% 
  na.omit()

## Manhattan plot
mh <- tasseldfVIC %>% 
  
  # Compute chromosome size
  group_by(Chr) %>% 
  summarise(chr_len=max(Pos)) %>% 
  
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  
  # Add this info to the initial dataset
  left_join(tasseldfVIC, ., by=c("Chr"="Chr")) %>%
  
  # Add a cumulative position of each SNP
  arrange(Chr, Pos) %>%
  mutate(BPcum=Pos+tot)

axisdf = mh %>% group_by(Chr) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )


ggplot(mh, aes(x=BPcum, y=-log10(p))) +
  geom_point( aes(color=as.factor(Chr)), alpha=0.7, size=1) +
  scale_color_manual(values = rep(c("#F6A316", "black"), 22 )) +
  # custom X axis:
  scale_x_continuous( label = axisdf$Chr, breaks= axisdf$center ) +
  labs(x = "Scaffolds", y = "-log10(p) [Bonferroni threshold]") +
  # Custom the theme:
  theme_bw() +
  theme( 
    legend.position="none",
    panel.border = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()) +
  ylim(0,150) +
  geom_hline(yintercept = -log10(max(vic_SNPs$associated_SNP_p)), linetype = "longdash") 
 

ggsave("plots/SupplFig5_vic.associations.pdf", useDingbats=F, height = 5, width = 5)
```
